http:
  port: 80
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

postgres:
  username: "tusk"
  host: "dpg-d6t9h9cr85hc739amrt0-a.frankfurt-postgres.render.com"
  port: "5432"
  dbname: "walrus_u0i2"
  sslmode: "require"
  password: "i4OcP4ui3CTUQ8lSejE0lQfFO8bR0uba"
  schema: "public"
  poolMax: 50
  poolMin: 20
  healthCheckPeriod: 10s
  connectionMaxIdleTime: 600s
  connectionMaxLifeTime: 1800s

log:
  level: "INFO"
  requestLogEnabled: true
  requestLogWithBody: true

internal:
  path: "/wn"
  environment: ".env"
  logInputParamOnErr: true
  encryptKey: "VerySecureEncryptKey"

cache:
  url: "localhost:6379"
  username: ""
  password: ""

response:
  exportError: true

email:
  ownerEmail: "support@walrus-notes.ru"
  addres: "smtp.gmail.com:587"
  codeLenght: 6
  codeExp: "5m"
  minTTL: "5m"

jwt:
  accessTtl: "100000h"
  refreshTtl: "1000h"

cron:
  generateStatics: "@every 5s"