// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/wn/api/v1/auth/code": {
            "post": {
                "description": "register new user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "send_confirm_code",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_dto_request.LoginRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wn_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wn_internal_domain_dto_response.SendCodeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: incorrect_password",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: user_not_found, confirm_code_already_send",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/auth/confirm": {
            "post": {
                "description": "Подтверждение кода для подтверждения почты, либо сброса пароля. Если сброс пароля, то newPassword обязательное поле.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "confirm_code",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_dto_request.ConfimationCodeRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: user_not_found, confirm_code_incorrect, confirm_code_not_exist, no_new_password",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/auth/forgot": {
            "post": {
                "description": "Сброс пароля",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "forgot_password",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_dto_request.LoginRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wn_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wn_internal_domain_dto_response.SendCodeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: user_not_found, confirm_code_already_send",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/auth/login": {
            "post": {
                "description": "Получение access,refresh токенов по почте и паролю",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_dto_request.LoginRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wn_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wn_internal_domain_dto_response.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "possible codes: incorrect_password",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: user_not_found ",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/auth/refresh": {
            "post": {
                "description": "Получение access,refresh токенов по access, refresh токенам",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "refresh_tokens",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_services_token.UserTokens"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wn_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wn_internal_domain_services_token.UserTokens"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: bad_refresh_token, bad_access_token, bad_token_claims, token_dont_exist, tokens_dont_match",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/auth/register": {
            "post": {
                "description": "register new user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "register_user",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_dto_request.RegisterCredentials"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wn_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wn_internal_domain_dto_response.RegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: not_unique",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/layout/create": {
            "post": {
                "description": "Создать новый layout",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "layouts"
                ],
                "summary": "create_layout",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_dto_request.NewLayoutRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wn_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wn_internal_domain_dto_response.NoteId"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/layout/my": {
            "get": {
                "description": "Получить все layout-ы, к которым имеет доступ пользователь",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "layouts"
                ],
                "summary": "get_my_layouts",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_dto_request.NoteId"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/notes/create": {
            "post": {
                "description": "Создать заметку",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notes"
                ],
                "summary": "create_note",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_dto_request.NoteRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wn_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wn_internal_domain_dto_response.NoteId"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: not_unique",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/notes/delete": {
            "post": {
                "description": "Удалить заметку",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notes"
                ],
                "summary": "delete_note",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_dto_request.NoteId"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: note_not_found",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/notes/layout": {
            "get": {
                "description": "Получить все заметки из layout-а",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notes"
                ],
                "summary": "get_notes_from_layout",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "layoutId",
                        "name": "layoutId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_query, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: note_not_found",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/notes/layout/graph/note": {
            "post": {
                "description": "Обновить позицию заметки в графе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "update_note_position",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_dto_request.UpdateNotePositionRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/notes/layout/graph/posed": {
            "get": {
                "description": "Получить заметки, которые имеют позиции в графе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "get_posed_notes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "layoutId",
                        "name": "layoutId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/notes/layout/graph/unposed": {
            "get": {
                "description": "Получить заметки, которые не имеют позиции в графе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "get_unposed_notes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "layoutId",
                        "name": "layoutId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/notes/update": {
            "post": {
                "description": "Обновить заметку",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notes"
                ],
                "summary": "update_note",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_dto_request.NoteWithIdRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: note_not_found",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/user/picture": {
            "post": {
                "description": "сменить аватарку пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "change_profile_picture",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wn_internal_domain_dto_request.ChangeProfilePicture"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wn_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wn_internal_domain_dto_response.ChangePictureResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_body, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: user_not_found",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/wn/api/v1/user/profile/{id}": {
            "get": {
                "description": "получить юзера по айди",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get_user_by_id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request id identity",
                        "name": "X-Request-Id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/wn_pkg_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/wn_internal_domain_dto_user.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "possible codes: bind_path, invalid_X-Request-Id",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    },
                    "422": {
                        "description": "possible codes: user_not_found",
                        "schema": {
                            "$ref": "#/definitions/wn_pkg_response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "multipart.FileHeader": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "header": {
                    "$ref": "#/definitions/textproto.MIMEHeader"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "textproto.MIMEHeader": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        },
        "wn_internal_domain_dto_request.ChangeProfilePicture": {
            "type": "object",
            "required": [
                "file"
            ],
            "properties": {
                "file": {
                    "$ref": "#/definitions/multipart.FileHeader"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_dto_request.ConfimationCodeRequest": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_dto_request.LoginRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_dto_request.NewLayoutRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_dto_request.NoteId": {
            "type": "object",
            "required": [
                "noteId"
            ],
            "properties": {
                "noteId": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_dto_request.NoteRequest": {
            "type": "object",
            "properties": {
                "layoutId": {
                    "type": "string"
                },
                "payload": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_dto_request.NoteWithIdRequest": {
            "type": "object",
            "required": [
                "noteId"
            ],
            "properties": {
                "noteId": {
                    "type": "string"
                },
                "payload": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_dto_request.RegisterCredentials": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_dto_request.UpdateNotePositionRequest": {
            "type": "object",
            "required": [
                "layoutId",
                "noteId"
            ],
            "properties": {
                "layoutId": {
                    "type": "string"
                },
                "noteId": {
                    "type": "string"
                },
                "xPos": {
                    "type": "number"
                },
                "yPos": {
                    "type": "number"
                }
            }
        },
        "wn_internal_domain_dto_response.ChangePictureResponse": {
            "type": "object",
            "properties": {
                "newImgUrl": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_dto_response.LoginResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_dto_response.NoteId": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_dto_response.RegisterResponse": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_dto_response.SendCodeResponse": {
            "type": "object",
            "properties": {
                "nextCodeDelay": {
                    "$ref": "#/definitions/time.Duration"
                }
            }
        },
        "wn_internal_domain_dto_user.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imgUrl": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "wn_internal_domain_services_token.UserTokens": {
            "type": "object",
            "required": [
                "accessToken",
                "refreshToken"
            ],
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "wn_pkg_response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/wn_pkg_response.meta"
                },
                "pagination": {
                    "$ref": "#/definitions/wn_pkg_response.pagination"
                }
            }
        },
        "wn_pkg_response.meta": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                }
            }
        },
        "wn_pkg_response.pagination": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "WALRUS NOTES API",
	Description:      "This is walrus notes api service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
